"""
functions/crisis_lookup.py

Resolves the {{CRISIS_LINE}} placeholder (used in the safety layer's training
examples) into the real contact, based on the user's country. The number is
NEVER generated by the model - it's always inserted here, deterministically,
from data/crisis_lines_full.json.

Typical usage inside the main conversation loop:

    from functions.crisis_lookup import resolve_crisis_placeholder

    response = fine_tuned_model.generate(...)
    response = resolve_crisis_placeholder(response, user_country, lang="pt")
"""
import json
from pathlib import Path

CRISIS_LINES_PATH = Path(__file__).resolve().parent.parent / "data" / "crisis_lines_full.json"
PLACEHOLDER = "{{CRISIS_LINE}}"

# Manual index: which of the several entries for each country (see
# crisis_lines_full.json) is the "primary" one to show by default. Fill this
# in as you confirm priority countries - never pick an entry with no numbers
# (see _pick_entry).
PRIMARY_ENTRY_INDEX = {
    "Portugal": 1,        # SOS Voz Amiga
    "United States": 1,   # 988 Suicide & Crisis Lifeline
    "United Kingdom": 4,  # Samaritans, 116 123
    "Brazil": 0,          # CVV
    "Spain": 0,           # Línea 024
}

# Note: these values are actual user-facing content shown to the person
# (not code comments), so they intentionally stay in the target language.
FALLBACK_MESSAGE = {
    "pt": "uma linha de apoio verificada em befrienders.org ou findahelpline.com",
    "en": "a verified support line at befrienders.org or findahelpline.com",
}

_cache = None


def _load():
    global _cache
    if _cache is None:
        with open(CRISIS_LINES_PATH, encoding="utf-8") as f:
            _cache = json.load(f)
    return _cache


def _pick_entry(country: str, age: int | None = None) -> dict | None:
    """Picks the entry to use for a country.

    If `age` is given, first tries to find a line meant for that audience
    (e.g. elderly, 65+; children/youth, <18) using each entry's "audience"
    field. If there's no audience-specific line for that country (the most
    common case - see note below), falls back to the default behaviour:
    PRIMARY_ENTRY_INDEX, or the first entry that has a number.

    Note: as of this implementation, out of 214 lines across 102 countries,
    only 1 is specific to the elderly (Greece) - so for the vast majority of
    countries, this will always fall back to default behaviour even when an
    age is passed. This isn't a bug, it's a real limit of the publicly
    available data.
    """
    countries = _load()["countries"]
    entries = countries.get(country)
    if not entries:
        return None

    if age is not None:
        target_audience = None
        if age >= 65:
            target_audience = "elderly"
        elif age < 18:
            target_audience = "children_youth"

        if target_audience:
            for entry in entries:
                if target_audience in entry.get("audience", []) and entry["numbers_found"]:
                    return entry
            # no audience-specific line for this country -> fall back to default behaviour

    idx = PRIMARY_ENTRY_INDEX.get(country)
    if idx is not None and idx < len(entries) and entries[idx]["numbers_found"]:
        return entries[idx]

    for entry in entries:
        if entry["numbers_found"]:
            return entry

    return None  # no entry for this country has a usable number


def get_crisis_line_text(country: str, lang: str = "pt", age: int | None = None) -> str:
    """Returns the text ready to insert in place of {{CRISIS_LINE}}."""
    entry = _pick_entry(country, age=age)
    if entry is None:
        return FALLBACK_MESSAGE.get(lang, FALLBACK_MESSAGE["en"])
    return ", ".join(entry["numbers_found"])


def resolve_crisis_placeholder(response_text: str, country: str, lang: str = "pt", age: int | None = None) -> str:
    """Replaces the {{CRISIS_LINE}} placeholder in the model's response with
    the real contact. If the placeholder isn't present, returns the text unchanged."""
    if PLACEHOLDER not in response_text:
        return response_text
    return response_text.replace(PLACEHOLDER, get_crisis_line_text(country, lang, age=age))


if __name__ == "__main__":
    example = "Please reach out to {{CRISIS_LINE}} right now, they're trained to help."
    print(resolve_crisis_placeholder(example, "Portugal"))
    print(resolve_crisis_placeholder(example, "United States"))
    print(resolve_crisis_placeholder(example, "Ruritania", lang="en"))  # non-existent country

    print()
    print("--- With age (audience-based personalization) ---")
    print("Greece, age 70 (should pick the elderly line):")
    print(" ", get_crisis_line_text("Greece", age=70))
    print("Greece, age 30 (should pick the general line, not elderly):")
    print(" ", get_crisis_line_text("Greece", age=30))
    print("Portugal, age 70 (no elderly line available -> falls back to default):")
    print(" ", get_crisis_line_text("Portugal", age=70))
